name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Ganti sesuai versi Flutter kamu

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze (ignore warnings)
        run: |
          flutter analyze || true

      - name: Build APK
        run: flutter build apk --debug
