name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Ganti sesuai versi Flutter kamu

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer (ignore warning)
        run: flutter analyze || true

      - name: Run unit tests (optional bypass)
        run: flutter test || true

      - name: Build APK (debug)
        run: flutter build apk --debug
